---
- name: GENERATE DEVICE CONFIGS
  hosts: platforms_eos
  connection: "local"
  roles:  
    - arista_render_config
  tasks:
    - name: "Push CONFIGS"
      arista.eos.eos_config:
        src: "configs/{{ inventory_hostname }}.eos"
        save_when: changed
      diff: true

