- name: Print OSPF
  ansible.builtin.debug:
    msg: "Router {{ inventory_hostname }} will run OSPF"
  tags: [ospf, routing]

- name: Print BGP
  ansible.builtin.debug:
    msg: "Router {{ inventory_hostname }} will run BGP"
  tags: [bgp, routing]

- name: Print NTP
  ansible.builtin.debug:
    msg: "Router {{ inventory_hostname }} will run NTP"
  tags: ntp
